# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology_json', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
