# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkTopology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='topology_name',
            field=models.CharField(default='No_Name_Provided', max_length=25),
        ),
    ]
