# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkTopology', '0002_topology_topology_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(default='NO_APP_NAME_PROVIDED', max_length=25)),
                ('application_requirements', django_mysql.models.JSONField(default=dict)),
                ('application_image', models.ImageField(default='NULL', upload_to='application_images')),
            ],
        ),
    ]
