# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkTopology', '0003_networkapplications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkapplications',
            name='application_image',
        ),
    ]
