# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkTopology', '0004_remove_networkapplications_application_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkapplications',
            name='application_config_file',
            field=models.FileField(default='NO_FILE_PROVIDED', upload_to='config'),
        ),
    ]
